### ISSUE TITLE
Bug: detectAdConfiguration returns "unclear" after consent

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bocops/UMP-workarounds#4] opened 2023-12-18 09:08 UTC
I use this to simulate the ad-consent:

```
            val params = ConsentRequestParameters
                .Builder()
                .setTagForUnderAgeOfConsent(false)
            if (BuildConfig.DEBUG) {
                val debugGeography =
                        ConsentDebugSettings.DebugGeography.DEBUG_GEOGRAPHY_EEA  
                val debugSettings = ConsentDebugSettings.Builder(app)
                    .setDebugGeography(debugGeography)
                    .addTestDeviceHashedId(SystemUtils.getDeviceHashedId(app)!!.uppercase())
                    .build()
                params.setConsentDebugSettings(debugSettings)
            }
```

Issue:

Before seeing the UI of `UserMessagingPlatform.loadAndShowConsentFormIfRequired`, when I use `detectAdConfiguration`, I get NONE, which makes sense.
However, when I press "consent" button, and check it out later (either in current session or later after the process is killed) , I get "UNCLEAR".

How so?

**Comment by bocops** [comment] 2023-12-18 09:28
Have you set `goodVendorConfiguration` to anything valid?

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 09:53
Not sure how to set it. It says in code:

```
        // TODO vendor configuration is variable, so needs to be defined by the individual developer
        //   - run app and make sure that a valid configuration is stored
        //   - have the app log the value of [tcVendorString], then copy that value to the following line
        //   - repeat if ad configuration changes, perhaps make this value available via remote configuration instead
        val goodVendorConfiguration = "TODO"
```

The code should work for all apps, for all devices, no?
If I set it to myself based on my observation on one device, what would it mean for others?
I don't understand how to set it up, and why it's here.

**Comment by bocops** [comment] 2023-12-18 10:16
The problem here is that, while all other checks are based on what fixed level of "consent" or "legitimate interest" Google needs to serve ads, the exact vendor list that an app user needs to accept will be different between apps, because it is something configured by the developer via their AdMob settings.

That is why the comment states that you should start your app, then consent to all in the UMP dialog, and subsequently should output whatever the vendor configuration looks like after you've consented to them all. You can do this using a function like this:

```kotlin
fun outputVendorString(context: Context) {
    val sp = PreferenceManager.getDefaultSharedPreferences(context)
    val tcVendorString = sp.getString("IABTCF_VendorConsents", null)
    Log.d("UMP vendor string", tcVendorString ?: "not stored")
}
```

If you call that function, you should see a lengthy bit string in your logcat output. Copy that value to your declaration of `goodVendorConfiguration` and remove the function call to output the string, and you should be set up properly until you change your vendor configuration in AdMob.

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 11:09
The reason I use this function is less than what it says it's doing. I just wanted to know if there was a consent of any kind, to see if it's ok to request ads now. For this I think I only need to check if it returns "None" or not, no?

I think the order of the checks should be improved.
The part with "maxAdDisplayConfiguration" should be later, as only later it's used. Same for tcVendorString. 
Before all, sufficientInterest is being checked, as it's the most important one, to differentiate between "None" and the rest.

Meaning it should be in this order:

```
sufficientInterest...
if (!sufficientInterest) {
   return AdConfiguration.NONE
   }
tcVendorString...
goodVendorConfiguration...
if (tcVendorString.length < goodVendorConfiguration.length) {
    return AdConfiguration.UNCLEAR
}
maxAdDisplayConfiguration...
```

As for goodVendorConfiguration  , it's weird for me. You say that each vendor has its own rules of what is the definition of which ad? There is no way to have a general solution for all people who use this function?

**Comment by bocops** [comment] 2023-12-18 11:19
It is not that individual vendors might have different rules, but that _you_ as an app developer might want to use different vendors in your AdMob configuration for app A vs. app B, and that another developer in their app C might use yet another list of vendors.

Ads will only _definitely_ be shown if an app user gave consent for all vendors that AdMob might serve an ad from, so this developer-defined list of vendors needs to be a part of the check.

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 11:26
Even weirder. It depends on a list of vendors that I choose...
Why does it depend on the list? The list can change all the time. 
Why should adding/removing an item there affect the result of which type of consent the user has chosen? 

It's quite hard to manage this way.

Can I at least assume that the "None" vs the rest is reliable?

**Comment by bocops** [comment] 2023-12-18 12:00
That is not a problem with the code in this repository, but with how Google's UMP and AdMob are set up. For your own use, you can edit the code as you like, which includes removing the whole vendor check part.

That doesn't change the fact that AdMob might not serve ads even if the remainder of the check claims that some incomplete consent has been provided.

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 13:02
1. If you are talking about the order, I mean that the order should be better because you don't need to query A&B , and then check just A and return, and later check result of B. You can query A and check it and return if needed, and then query B and check it.

2. About the vendors things, how does `ConsentInformation.canRequestAds()` work without checking any values of vendors that depends on how I've set the list of them?

3. Can you please at least tell me if the `ConsentInformation.canRequestAds()` works similar to this function , then (when the data is cached):

```
    fun canRequestAds(context: Context): Boolean {
        try {
            val detectAdConfiguration = detectAdConfiguration(context)
            return when (detectAdConfiguration) {
                AdConfiguration.ALL, AdConfiguration.NONPERSONALIZED, AdConfiguration.LIMITED, AdConfiguration.UNCLEAR -> true
                AdConfiguration.NONE -> false
            }
        } catch (e: Exception) {
        }
        return false
    }
```

?

This should be fine no matter the vendors check, according to what I've seen in code.

**Comment by bocops** [comment] 2023-12-18 13:21
I think the misunderstanding here is thinking that `canRequestAds()` is supposed to return `true` if ads can be displayed based on the consent given by a user, and `false` if not.

It would be great if it did that, and we've actually asked Google for that functionality for the last two years or more - but it does not perform this kind of check. All it does is tell us whether the purely legal prerequisites are valid. Basically, it returns true if the user has seen the UMP dialog, independent of what consent the user gave, or if the user does not need to see the dialog in the first place (for example because they live outside the EU).

If the user opted out of all possible consent, then ads can still be requested according to Google. There just won't be any ads served and displayed. The code we're discussing here fixes that exact shortcoming of Google's UMP, but can not force AdMob to serve ads for us to display.

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 13:43
About the "There just won't be any ads served and displayed", I think it's something people have complained about , but the general idea is that the ad-consent was at least shown to the user, so if the user has made a choice already, you need to respect it and start showing ads.
The reason for not showing ad in case the ad-consent wasn't given in any way, is (theoretically) because of no-fill due to the ad-networks not being able to handle it. This is why Google suggested to use multiple ad-networks.
Someone on reddit told me he integrated 15 (?!) ad networks to deal with this, as well as using a different mediation (CAS-AI) instead of Admob.

But is my assumption ok, that the function I've created above should work just as the original one of `ConsentInformation.canRequestAds()` (assuming the data is cached) ?

**Comment by bocops** [comment] 2023-12-18 14:47
> But is my assumption ok, that the function I've created above should work just as the original one of ConsentInformation.canRequestAds() (assuming the data is cached) ?

I do not know how Google's original function works, but among other things I am sure it returns true even if the user opted out of all necessary consent - basically, if our function here would return `AdConfiguration.NONE`, then `ConsentInformation.canRequestAds()` might still return true.

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 14:53
And sadly there is no way to check how their function works, as it's not open sourced...
Is there really nothing in the long docs of how you've found (to create your code here in this repository), that talks about this alone?

Also, will this at least be true:

detectAdConfiguration returns anything except None -> ConsentInformation.canRequestAds() should return true.

?

**Comment by bocops** [comment] 2023-12-18 15:24
That is likely true. If it is no longer `NONE` not long after a deletion, then the dialog must have been shown in the meantime, which means that UMP has been properly initialized and thus `canRequestAds()` should return true.

However, this is more a technicality than an actual success, though. First, if UMP has been initialized to show the dialog, you might as well just rely on `canRequestAds()` anyway. Second, you should consider the TCString deletion more of a desperate last resort than something to be done regularly. If you delete that string, all affected users _will_ have to click through the UMP dialog the next time they start your app - and if this happens too often, many of them will surely find out how to disable ads by just not consenting to anything.

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 15:34
But deleteTCStringIfOutdated is actually delete only once every year or so. I see this in code. 

In any case, you are saying that even though I might be right in terms of equivalent values (canRequestAds vs detectAdConfiguration ) , ads might not work properly till I call requestConsentInfoUpdate.
Correct?

While the docs say I should do it this way (always use requestConsentInfoUpdate before initialization of ads), I wonder if I can use the cached values from this repository, to reduce time before loading, and also to avoid being dependent on having an Activity all the time (one of the apps I work on have some scenarios of background operation and then an Activity  which shows ads).
I wonder if people have tested it.
Perhaps it will be clear only after the due date?

**Comment by AndroidDeveloperLB** [comment] 2023-12-18 22:01
Perhaps for the vendor part, this could help:
https://stackoverflow.com/questions/65351543/how-to-implement-ump-sdk-correctly-for-eu-consent/68310602#68310602
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#in-app-details

?

I don't see in their answer that you need to set "goodVendorConfiguration" or anything else...

**Comment by AndroidDeveloperLB** [comment] 2023-12-19 07:24
Google also said that it's ok to read the data and request ads before calling requestConsentInfoUpdate:

" If consent has already been gathered then the users consent choices will be respected. However, we recommend calling requestConsentInfoUpdate before doing so in the cases that consent may expire or ad partners being added/removed."

https://groups.google.com/g/google-admob-ads-sdk/c/UcveWmtBm4Q/m/G3RQOm00AwAJ

Then again, they wrong about the fact that getPrivacyOptionsRequirementStatus shouldn't return cached value (docs say it should), and that canRequestAds uses cache (and that's not even in the docs).

Anyway, this plan should be fine if they are correct about using the cache by ourselves:
1. If already got cached data that's not expired, use it.
2. Call requestConsentInfoUpdate. If you used the cached data, don't do anything about the result except for what's sadly doesn't work for now (getPrivacyOptionsRequirementStatus ). If you haven't used the cached data, use the new one.

**Comment by bocops** [comment] 2023-12-19 08:50
>https://stackoverflow.com/questions/65351543/how-to-implement-ump-sdk-correctly-for-eu-consent/68310602#68310602

They are doing the same thing, just not for an arbitrary set of vendors but restricted to AdMob, in the lines starting with `val googleId = 755`. If you, personally, only use AdMob and no other vendors via AdMob (mediation, waterfall, what-have-you, ...) in your app, then doing that is good enough. As soon as you have other vendors, you need to get consent for them.

Even your quote from Google mentions as much: "we recommend calling requestConsentInfoUpdate before doing so in the cases [...] or **ad partners being added/removed.**"

> https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#in-app-details

That resource just explains the different values that are stored by UMP (and other CMPs following IAB TCF). `IABTCF_VendorConsents` is the key that we're dealing with here.

**Comment by AndroidDeveloperLB** [comment] 2023-12-19 09:43
The quote wasn't to talk about the vendors. It was to show that I think it should be fine to have the plan I wrote about.

What they wrote in the context of what I asked them, is that requestConsentInfoUpdate should still be called (to get updated data at least for next time), but not that it would be the first step in case you want to use the cache to start loading ads. 
At least, that's what I understand here.
Do you agree that this plan should probably be fine?

About vendors, I see. Too bad. Was hoping it's a general solution. I don't get why the code there is quite different from here though, as it checks for more stuff and also 755 exists there... What would change if more vendors are at play there...

**Comment by bocops** [comment] 2023-12-19 10:24
`IABTCF_VendorConsents` is a bit string, where each "1" corresponds to a specific vendor that we've given consent for, and each "0" corresponds to a vendor that we've not given consent for.

If, in your AdMob configuration, only Google is activated as a vendor or "ad partner", then your users will only be asked to give consent for that single vendor. After they did give consent, the bit string will look like `000..0001`, with the single "1" in position 755, because that is the ID for Google.

However, if you need to gather consent for a dozen other ad partner, for example, because you use mediation/waterfall in AdMob, then there will be a dozen more "1" in positions corresponding to those vendors. There might be a "1" in position 92 if you use "1plusX AG", or in position 1111 if you use "152 Media LLC", or any other combination. Check [this](https://iabeurope.eu/vendor-list-tcf/) for a full list of vendor IDs.

The point is: only you know which combination of vendors are necessary for your app to show ads in all cases - so if that is what you want to check, you will bring your own vendor string to the table. If you don't want to check that, you can just remove that part of the function.

**Comment by AndroidDeveloperLB** [comment] 2023-12-19 10:36
A string of length 755 just because of bits?!
They could have at least compressed it to be based on bytes instead...

1. Why the need to check the vendors though? I know it says we should, but why? What does it mean? That the vendors are fine with the consent that the user has chosen and ready to show ads based on it?
2. If there is at least "1" inside, does it mean that ads can be requested, as at least one vendor is ok? Or it depends on which vendor it is? 
For example, if you use Admob as a mediation solution to host various ad-networks, yet Admob won't be fine (meaning it has "0"), but others will (so they have "1"), so you won't get ads of any vendor?

**Comment by bocops** [comment] 2023-12-19 10:48
Again, you can **request** ads whenever you like - the more important question is whether any will be **loaded** and **displayed** instead of just returning a "no fill".

Google states (for example as quoted above) that they will re-display the consent dialog after "ad partners [were] added/removed". This suggests that (a) they _do_ track that sort of stuff, and (b) that they consider it important before displaying ads.

I do _not_ know if they will drop the ad request altogether if given vendor consent does not match the currently configured list of vendors, or if they would just exclude those vendors from mediation individually, or if they just don't care because in the end it is your responsibility to have the necessary consent for whatever your app does.

**Comment by AndroidDeveloperLB** [comment] 2023-12-19 11:18
You don't mean that they will actively display the UI, right? You mean they will provide new information about needing it in the results of requestConsentInfoUpdate .

What I asked is about the plan, that if you already have a cached result from previous sessions (when it's not expired/updated), it should usually be fine to start requesting ads even before calling requestConsentInfoUpdate , and that it will be based on the consent of previous calls.
The only times you might lose is in the session that something has changed : Expired cache or something was updated. On the next session, you will be able to get new cached data again and/or have the UI shown too, depending on your app's logic.

So, for 99% of the times, you shouldn't get no-fill if you rely on cached data first.
And, as I use the deletion function of yours, the issue of expiration doesn't even exist, because the cache-check is done after deletion.
Only case that could be a problem is when things get updated, and this is very rare. Don't know if Admob gets updated automatically right after UI of the consent was handled or not, but it doesn't matter much as it's only for this rare scenario anyway.

**Comment by bocops** [comment] 2023-12-19 16:48
Yes, strictly speaking, `requestConsentInfoUpdate(...)` itself will not actively display any UI. I was considering their suggested way of calling `loadAndShowConsentFormIfRequired(...)` in the `OnConsentInfoUpdateSuccessListener` that is given as a parameter to the former function.

If all you want to do is decouple one and the other, you could just store the `ConsentStatus` value returned via that listener yourself, for the next app startup, while separately using whatever value you already have stored during _this_ app startup. In that case, you don't need any functionality of this repository.

I don't know if doing so is any good, or what the legal ramifications might be.

**Comment by AndroidDeveloperLB** [comment] 2023-12-19 17:15
I was hoping to use what's already saved, so that it will work exactly like of how ad-networks do it.

After testing further, I've noticed something that's weird for me:
Both canRequestAds and privacyOptionsRequirementStatus return false if I call them before calling requestConsentInfoUpdate , always.
However, if I call requestConsentInfoUpdate and then these (not inside the callback), it returns fine.
Sadly this means I still need to call requestConsentInfoUpdate which requires Activity, compared to just Context using the repository (or the class itself).
This isn't documented, but it's shown on their sample.
It's a bit better, but still bad.

**Comment by bocops** [comment] 2023-12-19 17:44
I've now added a new function similarly to what I've already suggested in a different thread. Please check: https://github.com/bocops/UMP-workarounds/tree/main/get_previous_consent_status/android/kotlin

Other than that, I think this thread has veered from its original topic far enough, and that original topic (returning UNCLEAR if no vendors are set) was not a bug in my code. I'm closing this one.

**Closed by bocops** 2023-12-19 17:44 UTC

**Comment by AndroidDeveloperLB** [comment] 2023-12-19 18:22
You mean this:

```
/**
 * Checks the SharedPreferences file created by Google UMP, and returns the int value of the cached consent status
 * according to https://developers.google.com/admob/android/privacy/api/reference/com/google/android/ump/ConsentInformation.ConsentStatus
 * These should be as follow:
 * 0 - UNKNOWN
 * 1 - NOT_REQUIRED
 * 2 - REQUIRED
 * 3 - OBTAINED
 */
private fun getPreviousConsentStatus(context: Context) {
    val sp = context.getSharedPreferences("__GOOGLE_FUNDING_CHOICE_SDK_INTERNAL__", Context.MODE_PRIVATE)
    return sp.getInt("consent_status", 0)
}
```


Doesn't seem like a valid function (no return type).
Why all the "private" again..
But this looks promising. Maybe better than the function I originally offered to use? Is it safe to assume that 1+3 mean that I should be able to request ads now ? 
How does it work with the expiration though? 
This time it doesn't go to the same file, so how does it handle it?

**Comment by bocops** [comment] 2023-12-19 18:51
> Doesn't seem like a valid function (no return type).
Fixed

> Why all the "private" again..
To be perfectly honest, I don't intend to spend more time debating each and every single decision, like whether a function is private or whether some order would make more sense than another in your opinion, for something that is basically a collection of concepts that might give other developers an idea of what works and what doesn't.

> But this looks promising. Maybe better than the function I originally offered to use? Is it safe to assume that 1+3 mean that I should be able to request ads now ?
1 and 3 should mean that, when these values were written, either didn't apply to the user running your app, or they were shown the UMP dialog. It is likely that this is still the case, though not  completely certain for all the reasons we discussed above.

> How does it work with the expiration though?
There's no timestamp stored in the preferences written by Google UMP, so you are on your own in that regard. You could get the consent timestamp using the other function, but that would be a somewhat sketchy thing to do because they come from different sources. You could also cache your own data and not rely on Google's preferences, as suggested further up above.

> This time it doesn't go to the same file, so how does it handle it?
I don't know what file (vs. what other file?) you are referring to.

**Comment by AndroidDeveloperLB** [comment] 2023-12-19 20:13
It's just that private functions aren't intended to be used by outside. 

About caching my own data, I'm not sure it's safe, as it might not be on time to get a refreshed data.
Better to rely on what's of the SDK.

About which file, I'm talking about the files that the function reaches : SharedPreferences file. It's different here than the one on the other functions (which is the default one instead).

**Comment by AndroidDeveloperLB** [comment] 2023-12-21 08:08
About the instruction here of setting goodVendorConfiguration based on what I get from tcVendorString:
https://github.com/bocops/UMP-workarounds/issues/4#issuecomment-1860023070

I copied the long string there. It has multiple "1" there for some reason. Not just a single one. That's even though on this app I use only Admob.

If I close/dismiss the dialog, or choose "do not consent", it's just "0", and yet the function returns "unclear".
Is it really unclear? Shouldn't it be limited or non-personalized?
We can at least say that it's not "personalized" for sure, no?
Maybe you should add a new function, of detection of "do no consent" ? 

I also don't know what happens if the user configures specific vendors there. There are many options for the users. 
Maybe possible to have different ad-types for different vendors...
I can't find how to see the ID of all vendors, and in your code there is no mention of 755. Only this string that I need to set.

**Comment by bocops** [comment] 2023-12-21 12:23
Discussion continued in #10.
